Docs Updates
DefangLabs/defang-docs pull request #106
Opened 2024-10-16 23:53 UTC by raphaeltm

2024-10-16 23:57 UTC, Prakash-Sundaresan requested changes
See detailed comments

2024-10-16 23:57 UTC, Prakash-Sundaresan commented on docs/concepts/debug.md
> +The AI debugger currently only works in Playground.
Say something about Debug on BYOC coming soon.

2024-10-16 23:57 UTC, Prakash-Sundaresan commented on docs/concepts/debug.md
> +The AI debugger only kicks in when the service fails to deploy. At the moment, we do not offer any way to trigger the AI debugger manually.
Is this true? Doesn't it kick in if the Deploy succeeds but healthcheck fails?

2024-10-17 00:06 UTC, raphaeltm commented on docs/concepts/debug.md
> +The AI debugger only kicks in when the service fails to deploy. At the moment, we do not offer any way to trigger the AI debugger manually.
What you're describing is what I would call a failed deployment.

2024-10-17 00:08 UTC, raphaeltm commented on docs/concepts/debug.md
> +The AI debugger only kicks in when the service fails to deploy. At the moment, we do not offer any way to trigger the AI debugger manually.
Also, I just double checked with @lionello and it gets triggered for other deployment failures as well: "anything except compose syntax errors"

2024-10-17 00:50 UTC, raphaeltm commented on docs/concepts/debug.md
> +The AI debugger only kicks in when the service fails to deploy. At the moment, we do not offer any way to trigger the AI debugger manually.
@Prakash-Sundaresan I updated with more details about different potential failure cases.

2024-10-17 22:57 UTC, merged