Document BYOC AWS Managed Resources
DefangLabs/defang-docs pull request #98
Opened 2024-09-24 19:33 UTC by jordanstephens

TODO
- [x] List all resources created by defang in your account for bootstrapping
- [x] List all resources created by defang for each project

2024-09-24 23:28 UTC, jordanstephens commented
@lionello I suspect some of these resources aren't in the right category, so double check my partitioning.

2024-10-16 20:36 UTC, lionello requested changes

2024-10-16 20:36 UTC, lionello commented on docs/providers/aws/aws.md
> +Then, defang will manage the following resources for each project you deploy:
Right now, in BYOC we bootstrap each project, so there's no infra shared between projects.

2024-10-16 21:46 UTC, jordanstephens commented on docs/providers/aws/aws.md
> +Then, defang will manage the following resources for each project you deploy:
That's what I intended to communicate by saying that the resources were managed "for each project" Is there a clearer way we can say that? Or should we just be extra explicit and add "None of these resources are shared between projects"?
```suggestion
Then, defang will manage the following resources for each project you deploy (None of these resources are shared between projects):
```

2024-10-17 02:03 UTC, lionello requested changes

2024-10-17 02:03 UTC, lionello commented on docs/providers/aws/aws.md
> +Defang will create and manage the following resources in your AWS account as part of its bootstrap procedure:
I don’t think this is correct. Here, I expected to see the resources in our CloudFormation stack.

2024-10-17 23:44 UTC, merged